# Write github workflows here

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Python
      run: |
        sudo apt-get update
        sudo apt-get install python3.8
        sudo apt-get install python3-pip
        python3 --version
    - name: Install Dependencies
      run: |
        python3 -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
    - name: Run Tests
      run: |
        python3 -m pip install pytest
        python3 -m pytest
   